# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectSave' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectSave

end

target 'ProjectSave-CoreData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectSave-CoreData

end

target 'ProjectSave-Realm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'
  # Pods for ProjectSave-Realm

end
